require "config.spec"
require "config.options"
require "config.keymaps"
require "config.autocmds"
spec "plugins.colorscheme"
spec "plugins.devicons"
spec "plugins.treesitter"
spec "plugins.mason"
spec "plugins.schemastore"
spec "plugins.lspconfig"
spec "plugins.null-ls"
spec "plugins.illuminate"
spec "plugins.telescope"
spec "plugins.telescope-tabs"
spec "plugins.nvimtree"
spec "plugins.lualine"
spec "plugins.whichkey"
spec "plugins.cmp"
spec "plugins.autopairs"
spec "plugins.comment"
spec "plugins.gitsigns"
spec "plugins.indentline"
spec "plugins.alpha"
spec "plugins.toggleterm"
spec "plugins.bufdelete"
-- Extras
spec "plugins.extras.neoscroll"
spec "plugins.extras.dressing"
spec "plugins.extras.leap"
spec "plugins.extras.todo-comments"
spec "plugins.extras.glance"
spec "plugins.extras.package-info"
-- spec "plugins.extras.surround"
-- spec "plugins.extras.eyeliner"
spec "plugins.extras.numb"
-- spec "plugins.extras.minifiles"
spec "plugins.extras.noice"
spec "plugins.extras.cmp-tabnine"
-- spec "plugins.extras.tabby"
require "config.lazy"
